Aspuri investment analysis on edgar using vss
aws-samples/amazon-neptune-samples pull request #135
Opened 2023-12-05 21:58 UTC by Angad02

*Description of changes:*
This repository contains a practical demo showcasing the concepts discussed in the "Investment Analysis using Vector Similarity in Amazon Neptune Analytics" blog series. The demo covers setting up a data pipeline to convert the raw EDGAR dataset to a Knowledge Graph, running Vector Similarity Search (VSS) combined with graph traversal queries, and provides a frontend for visualization.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-12-06 01:34 UTC, bechbd requested changes
Overall it is looking pretty good but need to do some cleanup of unneeded files and hardcoded values

2023-12-06 01:34 UTC, bechbd commented on investment-analysis-on-edgar-using-vss/README.md
> +This repository contains a practical demo showcasing the concepts discussed in the "Investment Analysis using Vector Similarity in Amazon Neptune Analytics" blog series. The demo covers setting up a
We should add a link to the EDGAR dataset here and a T&C associated with it

2023-12-06 01:34 UTC, bechbd commented on investment-analysis-on-edgar-using-vss/README.md
> +`s3://aws-neptune-customer-samples-us-east-1/sample-datasets/gremlin/edgar/`
We should add the other region links in there as well since you cannot load across regions

2023-12-06 01:34 UTC, bechbd commented on investment-analysis-on-edgar-using-vss/README.md
> +aws neptune-graph create-graph --graph-name 'edgar-vss'  --region us-east-1 --provisioned-memory 128 --allow-from-public --replica-count 0 --vector-search '{"dimension": 384}'
This might need to change with the upcoming SDK changes, we should verify once it is out

2023-12-06 01:34 UTC, bechbd commented on investment-analysis-on-edgar-using-vss/edgar_data_pipeline/S3_utils.py
> +        self.session = boto3.Session(profile_name='benchmark')
We should not have the hardcoded profile name in here, maybe allow them to pass the profile in as a parameter as well as choosing the default profile if one is not passed in

2023-12-06 01:34 UTC, bechbd commented on investment-analysis-on-edgar-using-vss/edgar_data_pipeline/S3_utils.py
> +            objects = self.s3.list_objects_v2(Bucket=self.s3_bucket, Prefix="data/CP/SemOpenAlex/v6/")
Why is the `Prefix` hardcoded to the SemOpenAlex dataset?

2023-12-06 01:34 UTC, bechbd commented on investment-analysis-on-edgar-using-vss/edgar_data_pipeline/S3_utils.py
> +    def list_all_files(self):
Where is this used and why is it hardcoded to IMDB?

2023-12-06 01:34 UTC, bechbd commented on investment-analysis-on-edgar-using-vss/edgar_data_pipeline/bedrock_api.py
> +        session = boto3.Session(profile_name='default')
Same previous on not hardcoding the session

2023-12-06 01:34 UTC, bechbd commented on investment-analysis-on-edgar-using-vss/edgar_data_pipeline/bedrock_api.py
> +        bedrock = session.client(service_name='bedrock-runtime', region_name='us-east-1')
Region should be a dynamic parameter, not static

2023-12-06 01:34 UTC, bechbd commented on investment-analysis-on-edgar-using-vss/edgar_data_pipeline/bedrock_api.py
> +                        model_kwargs={"max_tokens_to_sample": 1000, "temperature": 0.9})
Do you really want a temperature here >0?

2023-12-06 01:34 UTC, bechbd commented on investment-analysis-on-edgar-using-vss/edgar_data_pipeline/bedrock_api.py
> +        session = boto3.Session(profile_name='default')
See above comment on hard coded profile and region

2023-12-06 01:34 UTC, bechbd commented on investment-analysis-on-edgar-using-vss/edgar_frontend/kg_query_data_handler.py
> +    def generate_default_graph(self):
Remove this

2023-12-06 01:34 UTC, bechbd commented on investment-analysis-on-edgar-using-vss/neptune_analytics_integration/kg_query_executor.py
> +    # query_executor.query_top_companies_with_largest_holdings()
Remove these

2023-12-06 01:34 UTC, bechbd commented on investment-analysis-on-edgar-using-vss/neptune_analytics_integration/kg_query_executor.py
> +    print("hello World")
Remove

2023-12-06 01:34 UTC, bechbd commented on investment-analysis-on-edgar-using-vss/settings.py
> +graphId = "g-sqmear9347"
Do not store this in github, put in a Dummy Graph Id

2023-12-06 01:34 UTC, bechbd commented on investment-analysis-on-edgar-using-vss/neptune_analytics_integration/kg_query_executor.py
> +def main():
This does not appear to be used anywhere, am I missing where it is used or can this be removed?

2023-12-06 01:34 UTC, bechbd commented on investment-analysis-on-edgar-using-vss/neptune_analytics_integration/kg_query_executor.py
Where is this file used, all I saw referenced was the VSS one?

2023-12-06 01:34 UTC, bechbd commented on investment-analysis-on-edgar-using-vss/neptune_analytics_integration/vss_integration.py
> +            region_name="us-east-1",
See earlier comment on hard coding region name

2023-12-11 13:26 UTC, denisekgosnell reviewed
Need more end-to-end details on where we sourced this data, how we augmented it, and its format.

2023-12-11 13:26 UTC, denisekgosnell commented on investment-analysis-on-edgar-using-vss/README.md
> +For your convenience, we have already prepared the processed and ready-to-use EDGAR Knowledge Graph, which is stored at:
Please also detail: 1/ where to get the original data, 2/ how we sourced the descriptions, 3/ how we created the embeddings, and 4/ include a header of the first few lines to show the format.

2024-01-10 20:05 UTC, bechbd requested changes

2024-01-10 20:05 UTC, bechbd commented on investment-analysis-on-edgar-using-vss/README.md
> +The original data can be accessed from the U.S. Securities and Exchange Commission's EDGAR database at SEC's EDGAR Search and Access.
Can we add a link to the location here

2024-01-19 22:14 UTC, denisekgosnell commented on investment-analysis-on-edgar-using-vss/README.md
> +## Raw EDGAR Data Format
This is great.

Can you please provide the same header for the merged dataset that we curated?

2024-01-19 22:15 UTC, denisekgosnell commented on investment-analysis-on-edgar-using-vss/README.md
> +## Disclaimer for Data Accuracy
This is great - thank you.

2024-01-19 22:15 UTC, denisekgosnell commented on investment-analysis-on-edgar-using-vss/README.md
> +## Raw EDGAR Data Format
With the header of the curated dataset that we created for this; I approve this PR. Thank you, Angad!

2024-01-31 16:34 UTC, merged